# Generated by Django 2.0 on 2018-01-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='synonyms',
        ),
    ]
